add HUNO tracker
L4GSP1KE/Upload-Assistant pull request #73
Opened 2022-08-05 15:18 UTC by swannie-eire

all custom naming conventions are for this tracker is done in the huno class so wont affect others.

tested with 1 series and 2 movies and works as expected

2022-08-05 21:31 UTC, L4GSP1KE requested changes
There are a couple changes I'd like to see to bring this up to date and consistent with the other unit3d sites

2022-08-05 21:31 UTC, L4GSP1KE commented on src/trackers/HUNO.py
> +        if bool(distutils.util.strtobool(self.config['TRACKERS']['HUNO'].get('internal', "False"))) == False:
please change this internal config option to be consistent with the rest of the trackers. See below for implementation / usage: 

https://github.com/L4GSP1KE/Upload-Assistant/blob/f849e0b0e2e2ec444b42f15ec480e32122cecd76/src/trackers/AITHER.py#L83-L86 
https://github.com/L4GSP1KE/Upload-Assistant/blob/f849e0b0e2e2ec444b42f15ec480e32122cecd76/data/example-config.py#L84-L86

2022-08-05 21:31 UTC, L4GSP1KE commented on src/trackers/HUNO.py
> +    async def edit_desc(self, meta):
after changing to the shared unit3d description function you can delete this

2022-08-05 21:31 UTC, L4GSP1KE commented on src/trackers/HUNO.py
> +        await self.edit_desc(meta)
the edit_desc function doesn't seem to provide anything unique, so please use the shared unit3d description function. Example:

https://github.com/L4GSP1KE/Upload-Assistant/blob/f849e0b0e2e2ec444b42f15ec480e32122cecd76/src/trackers/AITHER.py#L34

2022-08-05 21:31 UTC, L4GSP1KE commented on src/trackers/HUNO.py
> +    async def edit_torrent(self, meta):
delete after changing to the shared edit_torrent function

2022-08-05 21:31 UTC, L4GSP1KE commented on src/trackers/HUNO.py
> +        await self.edit_torrent(meta)
please use the shared edit_torrent function
https://github.com/L4GSP1KE/Upload-Assistant/blob/f849e0b0e2e2ec444b42f15ec480e32122cecd76/src/trackers/AITHER.py#L33

2022-08-08 07:29 UTC, swannie-eire reviewed
added changes

2022-08-08 07:29 UTC, swannie-eire commented
I think i address everything you asked for.

Please have a look and let me know.

2022-08-08 18:50 UTC, merged

2022-08-08 18:50 UTC, L4GSP1KE commented
Looks good. Thanks